### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by JasurbekA** [Muhammadsher/github-readme-ranking#2]
Hey, thanks for the great ranking tool.

It seems it is not updating itself over time. The tool always shows the first generated result. Please update and auto-update ability

**Comment by Muhammadsher** [comment]
> Hey, thanks for the great ranking tool.
> 
> It seems it is not updating itself over time. The tool always shows the first generated result. Please update and auto-update ability

Hi @JasurbekA, This is the limitation of GitHub API, it restricts to limited number of requests per account, therefore, updates done only several times in a month.
